"""Add is_staff to user model

Revision ID: 0871206a0d06
Revises: f1fc73190c04
Create Date: 2026-06-09 12:31:38.029329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0871206a0d06'
down_revision: Union[str, Sequence[str], None] = 'f1fc73190c04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_staff', sa.Boolean(), nullable=True))
    op.execute("UPDATE users SET is_staff = FALSE")
    op.alter_column('users', 'is_staff', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_staff')
    # ### end Alembic commands ###
